---
- name: installtion and start apache http server
  hosts: all
  become: true
  tasks:
  - name: Installing apache http 
    yum:
      name: htt
      state: present
    tags: only install no service
    ignore_errors: yes

  - name: starting service  apache http
    service:
      name: httpd
      state: started
      enabled: yes



