---
- name: installtion copying inedx.html file and start apache http server
  hosts: all
  become: true
  tasks:
  - name: Installing apache http 
    yum:
      name: httpd
      state: present
  - name: copying index.html file
    copy: 
      src: /home/ansadmin/index.html
      dest: /var/www/html/
  - name: starting service  apache http
    service:
      name: httpd
      state: started
      enabled: yes



