---
- name: stop apache http server service uninstalltion
  hosts: all
  become: true
  
  tasks:
  - name: stopping service  apache http
    service:
      name: httpd
      state: stopped
   
  - name: uninstalling apache http
    yum:
      name: httpd
      state: absent



